server:
  port: 8082

spring:
  application:
    name: AuthenticationService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      initialization-fail-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HikariCP
  redis:
    database: 0
    host: ${AUTH_REDIS_HOST}
    port: ${AUTH_REDIS_PORT}
    password: ${AUTH_REDIS_PASSWORD}
    lettuce:
      pool:
        min-idle: 4
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  cloud:
    nacos:
      discovery:
        server-addr: ${AUTH_NACOS_SERVER_ADDR}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  url: ${AUTH_MINIO_URL}
  access-key: ${AUTH_MINIO_ACCESS_KEY}
  secret-key: ${AUTH_MINIO_SECRET_KEY}
